import AuthSessionProvider from '@/components/auth-session-provider';
import { NavBar } from '@/components/navbar';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Product',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={'bg-white'}>
        <AuthSessionProvider>
            <NavBar />
            {children}</AuthSessionProvider>
      </body>
    </html>
  );
}
