export const shoppingItems = [
  {
    CategoryId: 1,
    categoryName: 'Cemilan',
    sku: 'MHZVTK',
    name: 'Ciki ciki',
    description: 'Ciki ciki yang super enak, hanya di toko klontong kami',
    weight: 500,
    width: 5,
    length: 5,
    height: 5,
    image: '/cemilan.jpeg',
    harga: 30000,
  },
  {
    CategoryId: 2,
    categoryName: 'Minuman',
    sku: 'BTLJUS',
    name: 'Jus Apel',
    description: 'Segar dan menyehatkan, jus apel pilihan untuk kesehatan anda',
    weight: 1000,
    width: 10,
    length: 10,
    height: 30,
    image: '/jus_apel.jpeg',
    harga: 25000,
  },
  {
    CategoryId: 3,
    categoryName: 'Makanan',
    sku: 'NASPAD',
    name: 'Nasi Padang',
    description: 'Nikmati kelezatan nasi padang khas Sumatera Barat',
    weight: 800,
    width: 15,
    length: 20,
    height: 10,
    image: '/nasi_padang.jpeg',
    harga: 50000,
  },
  {
    CategoryId: 4,
    categoryName: 'Perabotan',
    sku: 'KMRTID',
    name: 'Tao Kae Noi',
    description: 'Makanan Seaweed enak',
    weight: 75000,
    width: 200,
    length: 200,
    height: 150,
    image: '/tao_kae_noi.jpeg',
    harga: 3500000,
  },
  // kitkat
  {
    CategoryId: 5,
    categoryName: 'Cemilan',
    sku: 'kitkat',
    name: 'Kitkat',
    description: 'Kitkat',
    weight: 3,
    width: 10,
    length: 10,
    height: 10,
    image: '/kitkat.jpeg',
    harga: 200000,
  },
  {
    CategoryId: 6,
    categoryName: 'Cleaning',
    // sabun
    sku: 'sabun',
    name: 'Sabun',
    description: 'Sabun mandi',
    weight: 1,
    width: 10,
    length: 10,
    height: 10,
    image: '/sabun.jpeg',
    harga: 5000,
  },
  {
    CategoryId: 18,
    categoryName: 'Makanan',
    sku: 'ROTI123',
    name: 'Roti',
    description: 'Roti tawar lembut dan segar, cocok untuk sarapan pagi Anda.',
    weight: 250,
    width: 10,
    length: 10,
    height: 5,
    image: '/roti.jpeg',
    harga: 15000,
  },
  {
    CategoryId: 19,
    categoryName: 'Obat Herbal',
    sku: 'TLKANGN',
    name: 'Tolak Angin',
    description:
      'Tolak Angin, obat herbal tradisional untuk menjaga stamina dan kesehatan Anda.',
    weight: 100,
    width: 3,
    length: 3,
    height: 10,
    image: '/tolak_angin.jpeg',
    harga: 10000,
  },
  {
    CategoryId: 20,
    categoryName: 'Minuman',
    sku: 'KOPTBRK',
    name: 'Kopi Tubruk',
    description:
      'Kopi Tubruk khas Indonesia, nikmati kehangatan dan kekentalan rasa kopi asli.',
    weight: 200,
    width: 5,
    length: 5,
    height: 10,
    image: '/kopi_tubruk.jpeg',
    harga: 20000,
  },
  {
    CategoryId: 20,
    categoryName: 'Minuman',
    sku: 'ESTMNSH',
    name: 'Es Teh Manis',
    description:
      'Segarkan hari Anda dengan Es Teh Manis yang manis dan menyegarkan.',
    weight: 500,
    width: 10,
    length: 10,
    height: 20,
    image: '/es_teh_manis.jpeg',
    harga: 15000,
  },
  {
    CategoryId: 20,
    categoryName: 'Minuman',
    sku: 'SPRITE',
    name: 'Sprite',
    description: 'Sprite, kesegaran lemon dan lime dalam setiap tegukan.',
    weight: 355,
    width: 6,
    length: 6,
    height: 20,
    image: '/sprite.avif',
    harga: 10000,
  },
  {
    CategoryId: 21,
    categoryName: 'Minuman',
    sku: 'OATMLK',
    name: 'Oatmilk',
    description:
      'Oatmilk, alternatif susu sehat dengan serat tinggi, baik untuk pencernaan.',
    weight: 950,
    width: 8,
    length: 8,
    height: 20,
    image: '/oatside.jpeg',
    harga: 30000,
  },
  {
    CategoryId: 22,
    categoryName: 'Makanan',
    sku: 'INDOMIE',
    name: 'Indomie',
    description:
      'Indomie, mie instan favorit yang lezat dan praktis untuk makan cepat Anda.',
    weight: 80,
    width: 10,
    length: 15,
    height: 5,
    image: '/indomie.jpeg',
    harga: 5000,
  },
];
